# Cargo config file

# Environment variables set for all `cargo...` commands.
[env]

# Scope down trasing.
RUST_LOG="rust_web_app=debug"

# Service Environment Variables
# IMPORTANt:
#   For cargo commands only
#   For deployed env should be managed by container
#   (e.g. K8s)

## -- ConfigMap
SERVICE_WEB_FOLDER="web-folder/"
